const fs = require('fs');

const NOW = new Date();

function addDays(base, days) {
  const d = new Date(base);
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

const MED_NAMES = [
  ["Paracetamol", "Analgesic", "Tablet", "500mg"],
  ["Amoxicillin", "Antibiotic", "Capsule", "250mg"],
  ["Ibuprofen", "NSAID", "Tablet", "400mg"],
  ["Cetirizine", "Antihistamine", "Tablet", "10mg"],
  ["Omeprazole", "PPI", "Capsule", "20mg"],
  ["Metformin", "Antidiabetic", "Tablet", "500mg"],
  ["Atorvastatin", "Statin", "Tablet", "40mg"],
  ["Amlodipine", "Calcium Channel Blocker", "Tablet", "5mg"],
  ["Losartan", "ARB", "Tablet", "50mg"],
  ["Lisinopril", "ACE Inhibitor", "Tablet", "10mg"],
  ["Albuterol", "Bronchodilator", "Inhaler", "90mcg"],
  ["Gabapentin", "Anticonvulsant", "Capsule", "300mg"],
  ["Sertraline", "SSRI", "Tablet", "50mg"],
  ["Escitalopram", "SSRI", "Tablet", "10mg"],
  ["Fluoxetine", "SSRI", "Capsule", "20mg"],
  ["Duloxetine", "SNRI", "Capsule", "30mg"],
  ["Azithromycin", "Antibiotic", "Tablet", "250mg"],
  ["Ciprofloxacin", "Antibiotic", "Tablet", "500mg"],
  ["Pantoprazole", "PPI", "Tablet", "40mg"],
  ["Metoprolol", "Beta Blocker", "Tablet", "50mg"]
];

const COLORS = ["#ef4444", "#f97316", "#f59e0b", "#eab308", "#84cc16", "#22c55e", "#10b981", "#14b8a6", "#06b6d4", "#0ea5e9", "#3b82f6", "#6366f1", "#8b5cf6", "#a855f7", "#d946ef", "#ec4899", "#f43f5e", "#64748b", "#71717a", "#78716c"];

const MEDICINES = MED_NAMES.map((m, i) => ({
  id: 1001 + i,
  name: `${m[0]} ${m[3]}`,
  genericName: m[0],
  manufacturer: i % 2 === 0 ? "PharmaCorp" : "MediLife",
  dosageForm: m[2],
  strength: m[3],
  storageCondition: "25°C / 60% RH",
  initialPotency: 100,
  category: m[1],
  color: COLORS[i]
}));

const BATCHES = [];

for (let i = 0; i < 50; i++) {
  const batchId = 101 + i;
  const medId = MEDICINES[i % 20].id;
  
  let daysOffset;
  if (i < 10) {
    // Expired
    daysOffset = -Math.floor(Math.random() * 100) - 1;
  } else if (i < 20) {
    // Critical (<= 7 days)
    daysOffset = Math.floor(Math.random() * 7) + 1;
  } else if (i < 35) {
    // Warning (<= 180 days)
    daysOffset = Math.floor(Math.random() * 160) + 10;
  } else {
    // Safe (> 180 days)
    daysOffset = Math.floor(Math.random() * 500) + 185;
  }
  
  const expiryDate = addDays(NOW, daysOffset);
  const mfgDate = addDays(new Date(expiryDate), -730); // 2 years ago
  
  const testIntervals = [];
  const intervals = [0, 3, 6, 9, 12, 18, 24];
  
  let currentAssay = 100.0;
  let currentDissolution = 98.5;
  let currentImpurity = 0.1;

  for (const month of intervals) {
    // Test if the month date is past NOW - if so, we shouldn't have data for it? 
    // Wait, the specification is just that they have these intervals tests. Let's just generate all them.
    
    currentAssay -= (Math.random() * 0.8 + 0.2);
    currentDissolution -= (Math.random() * 0.6 + 0.1);
    currentImpurity += (Math.random() * 0.2 + 0.05);
    
    testIntervals.push({
      month: month,
      assay: parseFloat(currentAssay.toFixed(2)),
      dissolution: parseFloat(currentDissolution.toFixed(2)),
      pH: parseFloat((5.5 + Math.random() * 0.5).toFixed(2)),
      moisture: parseFloat((2.0 + Math.random() * 1.5).toFixed(2)),
      impurity: parseFloat(currentImpurity.toFixed(2)),
      microbial: 10,
      passFail: currentAssay >= 90
    });
  }
  
  BATCHES.push({
    id: batchId,
    medicineId: medId,
    mfgDate: mfgDate,
    expiryDate: expiryDate,
    testIntervals: testIntervals
  });
}

const fileContent = `// AUTOGENERATED FROM SCRIPT
export const NOW = new Date();

export function addDays(base: Date, days: number): string {
  const d = new Date(base);
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}
export function subMonths(base: Date, months: number): string {
  const d = new Date(base);
  d.setMonth(d.getMonth() - months);
  return d.toISOString().split('T')[0];
}
export function daysFromNow(dateStr: string): number {
  return Math.ceil((new Date(dateStr).getTime() - NOW.getTime()) / 86400000);
}

export type ExpiryStatus = 'Expired' | 'Critical' | 'Warning' | 'Safe';
export function getStatus(expiryDate: string): ExpiryStatus {
  const d = daysFromNow(expiryDate);
  if (d <= 0) return 'Expired';
  if (d <= 7) return 'Critical';
  if (d <= 180) return 'Warning';
  return 'Safe';
}

export interface TestInterval { month: number; assay: number; dissolution: number; pH: number; moisture: number; impurity: number; microbial: number; passFail: boolean; }
export interface Batch { id: number; medicineId: number; mfgDate: string; expiryDate: string; testIntervals: TestInterval[]; }
export interface Medicine { id: number; name: string; genericName: string; manufacturer: string; dosageForm: string; strength: string; storageCondition: string; initialPotency: number; category: string; color: string; }

export const MEDICINES: Medicine[] = ${JSON.stringify(MEDICINES, null, 2)};
export const BATCHES: Batch[] = ${JSON.stringify(BATCHES, null, 2)};

export const BATCH_LIST = BATCHES.map(b => {
  const med = MEDICINES.find(m => m.id === b.medicineId)!;
  const status = getStatus(b.expiryDate);
  const days = daysFromNow(b.expiryDate);
  const lastTest = b.testIntervals[b.testIntervals.length - 1]! || { assay: 100 }; // fallback
  return { ...b, med, status, days, lastTest };
});

export const STATUS_COUNTS = {
  Expired:  BATCH_LIST.filter(b => b.status === 'Expired').length,
  Critical: BATCH_LIST.filter(b => b.status === 'Critical').length,
  Warning:  BATCH_LIST.filter(b => b.status === 'Warning').length,
  Safe:     BATCH_LIST.filter(b => b.status === 'Safe').length,
};

export const expiryDistributionData = [
  { name: 'Expired',  value: STATUS_COUNTS.Expired,  fill: '#ef4444' },
  { name: 'Critical', value: STATUS_COUNTS.Critical, fill: '#dc2626' },
  { name: 'Warning',  value: STATUS_COUNTS.Warning,  fill: '#f59e0b' },
  { name: 'Safe',     value: STATUS_COUNTS.Safe,     fill: '#22c55e' },
];

const mfgCounts: Record<string, number> = {};
BATCH_LIST.forEach(b => {
  const key = b.mfgDate.slice(0, 7);
  mfgCounts[key] = (mfgCounts[key] || 0) + 1;
});
export const manufactureDateData = Object.entries(mfgCounts)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([month, count]) => ({ month, batches: count }));

const expCounts: Record<string, number> = {};
BATCH_LIST.forEach(b => {
  if (b.days > 0) {
    const key = b.expiryDate.slice(0, 7);
    expCounts[key] = (expCounts[key] || 0) + 1;
  }
});
export const expiryByMonthData = Object.entries(expCounts)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([month, count]) => ({ month, batches: count }));

export const potencyTrendData = [0, 3, 6, 9, 12].map(month => {
  const row: Record<string, number | string> = { month: \`\${month}m\` };
  MEDICINES.forEach(med => {
    const batches = BATCHES.filter(b => b.medicineId === med.id);
    if(batches.length===0) return;
    const avg = batches.reduce((sum, b) => {
      const t = b.testIntervals.find(ti => ti.month === month);
      return sum + (t?.assay ?? 100);
    }, 0) / batches.length;
    row[med.name.split(' ')[0] || ('M'+med.id)] = +avg.toFixed(2);
  });
  return row;
});

export const testParamData = MEDICINES.map(med => {
  const latestTests = BATCHES.filter(b => b.medicineId === med.id).map(b => b.testIntervals[b.testIntervals.length - 1]!).filter(Boolean);
  if(latestTests.length===0) return { medicine: med.name.split(' ')[0] || ('M'+med.id), Assay:0, Dissolution:0, pH:0, Moisture:0, Impurity:0 };
  const avg = (key: keyof TestInterval) =>
    +(latestTests.reduce((s, t) => s + ((t && t[key] as number) || 0), 0) / latestTests.length).toFixed(2);
  return {
    medicine: med.name.split(' ')[0] || ('M'+med.id),
    Assay: avg('assay'),
    Dissolution: avg('dissolution'),
    pH: avg('pH'),
    Moisture: avg('moisture'),
    Impurity: avg('impurity'),
  };
});

export const passFailData = MEDICINES.map(med => {
  const allTests = BATCHES.filter(b => b.medicineId === med.id)
    .flatMap(b => b.testIntervals).filter(Boolean);
  return {
    medicine: med.name.split(' ')[0] || ('M'+med.id),
    Pass: allTests.filter(t => t.passFail).length,
    Fail: allTests.filter(t => !t.passFail).length,
  };
});
`

fs.writeFileSync('src/data/pharmaData.ts', fileContent);
console.log('Successfully wrote to src/data/pharmaData.ts');
