// AUTOGENERATED FROM SCRIPT
export const NOW = new Date();

export function addDays(base: Date, days: number): string {
  const d = new Date(base);
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}
export function subMonths(base: Date, months: number): string {
  const d = new Date(base);
  d.setMonth(d.getMonth() - months);
  return d.toISOString().split('T')[0];
}
export function daysFromNow(dateStr: string): number {
  return Math.ceil((new Date(dateStr).getTime() - NOW.getTime()) / 86400000);
}

export type ExpiryStatus = 'Expired' | 'Critical' | 'Warning' | 'Safe';
export function getStatus(expiryDate: string): ExpiryStatus {
  const d = daysFromNow(expiryDate);
  if (d <= 0) return 'Expired';
  if (d <= 7) return 'Critical';
  if (d <= 180) return 'Warning';
  return 'Safe';
}

export type UserRole = 'QA Manager' | 'Lab Technician';
export interface SystemTask { id: string; date: string; title: string; assigneeRole: UserRole; status: 'Pending' | 'Completed'; batchId?: number; }
export interface AuditLog { id: number; timestamp: string; user: string; action: string; details: string; }
export interface Chamber { id: string; name: string; temperature: string; humidity: string; nextCalibration: string; status: 'Active' | 'Maintenance' | 'Out of Calibration'; batchCount: number; }

export interface TestInterval { month: number; assay: number; dissolution: number; pH: number; moisture: number; impurity: number; microbial: number; passFail: boolean; }
export interface Batch { id: number; medicineId: number; mfgDate: string; expiryDate: string; testIntervals: TestInterval[]; }
export interface Medicine { id: number; name: string; genericName: string; manufacturer: string; dosageForm: string; strength: string; storageCondition: string; initialPotency: number; category: string; color: string; }

export const MEDICINES: Medicine[] = [
  {
    "id": 1001,
    "name": "Paracetamol 500mg",
    "genericName": "Paracetamol",
    "manufacturer": "PharmaCorp",
    "dosageForm": "Tablet",
    "strength": "500mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "Analgesic",
    "color": "#ef4444"
  },
  {
    "id": 1002,
    "name": "Amoxicillin 250mg",
    "genericName": "Amoxicillin",
    "manufacturer": "MediLife",
    "dosageForm": "Capsule",
    "strength": "250mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "Antibiotic",
    "color": "#f97316"
  },
  {
    "id": 1003,
    "name": "Ibuprofen 400mg",
    "genericName": "Ibuprofen",
    "manufacturer": "PharmaCorp",
    "dosageForm": "Tablet",
    "strength": "400mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "NSAID",
    "color": "#f59e0b"
  },
  {
    "id": 1004,
    "name": "Cetirizine 10mg",
    "genericName": "Cetirizine",
    "manufacturer": "MediLife",
    "dosageForm": "Tablet",
    "strength": "10mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "Antihistamine",
    "color": "#eab308"
  },
  {
    "id": 1005,
    "name": "Omeprazole 20mg",
    "genericName": "Omeprazole",
    "manufacturer": "PharmaCorp",
    "dosageForm": "Capsule",
    "strength": "20mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "PPI",
    "color": "#84cc16"
  },
  {
    "id": 1006,
    "name": "Metformin 500mg",
    "genericName": "Metformin",
    "manufacturer": "MediLife",
    "dosageForm": "Tablet",
    "strength": "500mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "Antidiabetic",
    "color": "#22c55e"
  },
  {
    "id": 1007,
    "name": "Atorvastatin 40mg",
    "genericName": "Atorvastatin",
    "manufacturer": "PharmaCorp",
    "dosageForm": "Tablet",
    "strength": "40mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "Statin",
    "color": "#10b981"
  },
  {
    "id": 1008,
    "name": "Amlodipine 5mg",
    "genericName": "Amlodipine",
    "manufacturer": "MediLife",
    "dosageForm": "Tablet",
    "strength": "5mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "Calcium Channel Blocker",
    "color": "#14b8a6"
  },
  {
    "id": 1009,
    "name": "Losartan 50mg",
    "genericName": "Losartan",
    "manufacturer": "PharmaCorp",
    "dosageForm": "Tablet",
    "strength": "50mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "ARB",
    "color": "#06b6d4"
  },
  {
    "id": 1010,
    "name": "Lisinopril 10mg",
    "genericName": "Lisinopril",
    "manufacturer": "MediLife",
    "dosageForm": "Tablet",
    "strength": "10mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "ACE Inhibitor",
    "color": "#0ea5e9"
  },
  {
    "id": 1011,
    "name": "Albuterol 90mcg",
    "genericName": "Albuterol",
    "manufacturer": "PharmaCorp",
    "dosageForm": "Inhaler",
    "strength": "90mcg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "Bronchodilator",
    "color": "#3b82f6"
  },
  {
    "id": 1012,
    "name": "Gabapentin 300mg",
    "genericName": "Gabapentin",
    "manufacturer": "MediLife",
    "dosageForm": "Capsule",
    "strength": "300mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "Anticonvulsant",
    "color": "#6366f1"
  },
  {
    "id": 1013,
    "name": "Sertraline 50mg",
    "genericName": "Sertraline",
    "manufacturer": "PharmaCorp",
    "dosageForm": "Tablet",
    "strength": "50mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "SSRI",
    "color": "#8b5cf6"
  },
  {
    "id": 1014,
    "name": "Escitalopram 10mg",
    "genericName": "Escitalopram",
    "manufacturer": "MediLife",
    "dosageForm": "Tablet",
    "strength": "10mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "SSRI",
    "color": "#a855f7"
  },
  {
    "id": 1015,
    "name": "Fluoxetine 20mg",
    "genericName": "Fluoxetine",
    "manufacturer": "PharmaCorp",
    "dosageForm": "Capsule",
    "strength": "20mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "SSRI",
    "color": "#d946ef"
  },
  {
    "id": 1016,
    "name": "Duloxetine 30mg",
    "genericName": "Duloxetine",
    "manufacturer": "MediLife",
    "dosageForm": "Capsule",
    "strength": "30mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "SNRI",
    "color": "#ec4899"
  },
  {
    "id": 1017,
    "name": "Azithromycin 250mg",
    "genericName": "Azithromycin",
    "manufacturer": "PharmaCorp",
    "dosageForm": "Tablet",
    "strength": "250mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "Antibiotic",
    "color": "#f43f5e"
  },
  {
    "id": 1018,
    "name": "Ciprofloxacin 500mg",
    "genericName": "Ciprofloxacin",
    "manufacturer": "MediLife",
    "dosageForm": "Tablet",
    "strength": "500mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "Antibiotic",
    "color": "#64748b"
  },
  {
    "id": 1019,
    "name": "Pantoprazole 40mg",
    "genericName": "Pantoprazole",
    "manufacturer": "PharmaCorp",
    "dosageForm": "Tablet",
    "strength": "40mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "PPI",
    "color": "#71717a"
  },
  {
    "id": 1020,
    "name": "Metoprolol 50mg",
    "genericName": "Metoprolol",
    "manufacturer": "MediLife",
    "dosageForm": "Tablet",
    "strength": "50mg",
    "storageCondition": "25°C / 60% RH",
    "initialPotency": 100,
    "category": "Beta Blocker",
    "color": "#78716c"
  }
];
export const BATCHES: Batch[] = [
  {
    "id": 101,
    "medicineId": 1001,
    "mfgDate": "2024-03-12",
    "expiryDate": "2026-03-12",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.4,
        "dissolution": 98.25,
        "pH": 5.75,
        "moisture": 3.02,
        "impurity": 0.29,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.89,
        "dissolution": 98.15,
        "pH": 5.86,
        "moisture": 2.01,
        "impurity": 0.46,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.51,
        "dissolution": 97.58,
        "pH": 5.94,
        "moisture": 2.49,
        "impurity": 0.56,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 98.13,
        "dissolution": 97.03,
        "pH": 5.98,
        "moisture": 2.1,
        "impurity": 0.8,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.75,
        "dissolution": 96.68,
        "pH": 5.87,
        "moisture": 3.46,
        "impurity": 0.96,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 97.43,
        "dissolution": 96.45,
        "pH": 5.8,
        "moisture": 3.48,
        "impurity": 1.2,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.62,
        "dissolution": 96.22,
        "pH": 5.66,
        "moisture": 3.17,
        "impurity": 1.34,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 102,
    "medicineId": 1002,
    "mfgDate": "2024-01-16",
    "expiryDate": "2026-01-15",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.5,
        "dissolution": 98.2,
        "pH": 5.55,
        "moisture": 2.14,
        "impurity": 0.17,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.28,
        "dissolution": 97.89,
        "pH": 5.72,
        "moisture": 2.11,
        "impurity": 0.3,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.81,
        "dissolution": 97.37,
        "pH": 5.8,
        "moisture": 2.72,
        "impurity": 0.42,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 98.47,
        "dissolution": 97,
        "pH": 5.77,
        "moisture": 2.26,
        "impurity": 0.6,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.97,
        "dissolution": 96.48,
        "pH": 5.66,
        "moisture": 2.69,
        "impurity": 0.82,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 97.76,
        "dissolution": 96.2,
        "pH": 5.75,
        "moisture": 2.09,
        "impurity": 1.05,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.86,
        "dissolution": 95.75,
        "pH": 5.8,
        "moisture": 2.76,
        "impurity": 1.2,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 103,
    "medicineId": 1003,
    "mfgDate": "2024-01-10",
    "expiryDate": "2026-01-09",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.63,
        "dissolution": 98.37,
        "pH": 5.92,
        "moisture": 2.59,
        "impurity": 0.22,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.13,
        "dissolution": 98.1,
        "pH": 5.9,
        "moisture": 2.73,
        "impurity": 0.43,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.67,
        "dissolution": 97.83,
        "pH": 5.78,
        "moisture": 2.89,
        "impurity": 0.55,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.96,
        "dissolution": 97.68,
        "pH": 5.64,
        "moisture": 2.76,
        "impurity": 0.73,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.56,
        "dissolution": 97.11,
        "pH": 5.96,
        "moisture": 2.68,
        "impurity": 0.81,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 97.26,
        "dissolution": 96.56,
        "pH": 5.82,
        "moisture": 3.43,
        "impurity": 0.91,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.72,
        "dissolution": 96.06,
        "pH": 5.9,
        "moisture": 3.01,
        "impurity": 0.99,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 104,
    "medicineId": 1004,
    "mfgDate": "2024-02-12",
    "expiryDate": "2026-02-11",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.2,
        "dissolution": 98.38,
        "pH": 5.65,
        "moisture": 2.16,
        "impurity": 0.33,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.68,
        "dissolution": 97.87,
        "pH": 5.71,
        "moisture": 2.46,
        "impurity": 0.58,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98,
        "dissolution": 97.73,
        "pH": 5.67,
        "moisture": 2.88,
        "impurity": 0.79,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.75,
        "dissolution": 97.38,
        "pH": 5.99,
        "moisture": 3.01,
        "impurity": 0.87,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.94,
        "dissolution": 96.72,
        "pH": 5.65,
        "moisture": 3.11,
        "impurity": 1.02,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.29,
        "dissolution": 96.24,
        "pH": 5.75,
        "moisture": 2.15,
        "impurity": 1.08,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.39,
        "dissolution": 95.91,
        "pH": 5.83,
        "moisture": 2.68,
        "impurity": 1.14,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 105,
    "medicineId": 1005,
    "mfgDate": "2024-01-10",
    "expiryDate": "2026-01-09",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.03,
        "dissolution": 97.8,
        "pH": 5.58,
        "moisture": 2.8,
        "impurity": 0.19,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.61,
        "dissolution": 97.22,
        "pH": 5.7,
        "moisture": 2.55,
        "impurity": 0.4,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.62,
        "dissolution": 96.84,
        "pH": 5.92,
        "moisture": 2.89,
        "impurity": 0.47,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 96.95,
        "dissolution": 96.55,
        "pH": 5.9,
        "moisture": 2.94,
        "impurity": 0.68,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.53,
        "dissolution": 96.03,
        "pH": 5.94,
        "moisture": 2.18,
        "impurity": 0.83,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.03,
        "dissolution": 95.62,
        "pH": 5.88,
        "moisture": 3.32,
        "impurity": 1.01,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.77,
        "dissolution": 95.01,
        "pH": 5.73,
        "moisture": 3.14,
        "impurity": 1.21,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 106,
    "medicineId": 1006,
    "mfgDate": "2024-01-27",
    "expiryDate": "2026-01-26",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.69,
        "dissolution": 97.9,
        "pH": 5.59,
        "moisture": 2.35,
        "impurity": 0.26,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.13,
        "dissolution": 97.29,
        "pH": 5.55,
        "moisture": 2.61,
        "impurity": 0.48,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.37,
        "dissolution": 97,
        "pH": 5.72,
        "moisture": 2.27,
        "impurity": 0.54,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.99,
        "dissolution": 96.61,
        "pH": 5.91,
        "moisture": 3.06,
        "impurity": 0.62,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.64,
        "dissolution": 96.05,
        "pH": 5.65,
        "moisture": 3.36,
        "impurity": 0.72,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.77,
        "dissolution": 95.69,
        "pH": 5.73,
        "moisture": 2.94,
        "impurity": 0.86,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.46,
        "dissolution": 95.4,
        "pH": 5.52,
        "moisture": 2.34,
        "impurity": 1.1,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 107,
    "medicineId": 1007,
    "mfgDate": "2024-01-31",
    "expiryDate": "2026-01-30",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.55,
        "dissolution": 97.94,
        "pH": 5.98,
        "moisture": 2.91,
        "impurity": 0.21,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.63,
        "dissolution": 97.66,
        "pH": 5.88,
        "moisture": 2.32,
        "impurity": 0.4,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.85,
        "dissolution": 97.35,
        "pH": 5.6,
        "moisture": 3.45,
        "impurity": 0.6,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.03,
        "dissolution": 97.24,
        "pH": 5.62,
        "moisture": 2.19,
        "impurity": 0.66,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.75,
        "dissolution": 96.88,
        "pH": 5.76,
        "moisture": 2.91,
        "impurity": 0.72,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.83,
        "dissolution": 96.24,
        "pH": 5.94,
        "moisture": 3.11,
        "impurity": 0.95,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.14,
        "dissolution": 96.13,
        "pH": 5.75,
        "moisture": 2.67,
        "impurity": 1.13,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 108,
    "medicineId": 1008,
    "mfgDate": "2024-02-12",
    "expiryDate": "2026-02-11",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.2,
        "dissolution": 98.36,
        "pH": 5.69,
        "moisture": 2.23,
        "impurity": 0.18,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.35,
        "dissolution": 97.96,
        "pH": 5.96,
        "moisture": 3.15,
        "impurity": 0.27,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.54,
        "dissolution": 97.86,
        "pH": 5.82,
        "moisture": 2.17,
        "impurity": 0.35,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.24,
        "dissolution": 97.56,
        "pH": 5.94,
        "moisture": 2.71,
        "impurity": 0.54,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.44,
        "dissolution": 97.37,
        "pH": 5.88,
        "moisture": 2.72,
        "impurity": 0.66,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.47,
        "dissolution": 96.92,
        "pH": 5.57,
        "moisture": 2.2,
        "impurity": 0.81,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 94.74,
        "dissolution": 96.27,
        "pH": 5.91,
        "moisture": 2.59,
        "impurity": 1,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 109,
    "medicineId": 1009,
    "mfgDate": "2024-02-07",
    "expiryDate": "2026-02-06",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.36,
        "dissolution": 98.26,
        "pH": 5.72,
        "moisture": 2.28,
        "impurity": 0.34,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.97,
        "dissolution": 98.09,
        "pH": 5.68,
        "moisture": 2.59,
        "impurity": 0.48,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.99,
        "dissolution": 97.56,
        "pH": 5.94,
        "moisture": 2.43,
        "impurity": 0.68,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.41,
        "dissolution": 96.99,
        "pH": 5.97,
        "moisture": 2.25,
        "impurity": 0.87,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.14,
        "dissolution": 96.49,
        "pH": 5.86,
        "moisture": 3.09,
        "impurity": 0.95,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.71,
        "dissolution": 96.05,
        "pH": 5.51,
        "moisture": 2.6,
        "impurity": 1.18,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.97,
        "dissolution": 95.67,
        "pH": 5.7,
        "moisture": 2.72,
        "impurity": 1.41,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 110,
    "medicineId": 1010,
    "mfgDate": "2024-02-19",
    "expiryDate": "2026-02-18",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.16,
        "dissolution": 97.88,
        "pH": 5.57,
        "moisture": 3.4,
        "impurity": 0.25,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.31,
        "dissolution": 97.59,
        "pH": 5.6,
        "moisture": 2.22,
        "impurity": 0.45,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.36,
        "dissolution": 96.92,
        "pH": 5.66,
        "moisture": 3.34,
        "impurity": 0.55,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.1,
        "dissolution": 96.25,
        "pH": 5.82,
        "moisture": 2.86,
        "impurity": 0.67,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.87,
        "dissolution": 95.63,
        "pH": 5.91,
        "moisture": 3.25,
        "impurity": 0.9,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.13,
        "dissolution": 95.48,
        "pH": 5.6,
        "moisture": 2.08,
        "impurity": 1.07,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.89,
        "dissolution": 94.86,
        "pH": 5.79,
        "moisture": 2.19,
        "impurity": 1.16,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 111,
    "medicineId": 1011,
    "mfgDate": "2024-03-23",
    "expiryDate": "2026-03-23",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.58,
        "dissolution": 98.38,
        "pH": 5.87,
        "moisture": 2.04,
        "impurity": 0.18,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.07,
        "dissolution": 97.81,
        "pH": 5.57,
        "moisture": 2.14,
        "impurity": 0.36,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.09,
        "dissolution": 97.39,
        "pH": 5.55,
        "moisture": 2.58,
        "impurity": 0.44,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.74,
        "dissolution": 97.01,
        "pH": 5.59,
        "moisture": 2.77,
        "impurity": 0.61,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.08,
        "dissolution": 96.45,
        "pH": 5.51,
        "moisture": 2.02,
        "impurity": 0.74,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.5,
        "dissolution": 96.07,
        "pH": 5.65,
        "moisture": 3.35,
        "impurity": 0.93,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.68,
        "dissolution": 95.38,
        "pH": 5.97,
        "moisture": 3.18,
        "impurity": 1.02,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 112,
    "medicineId": 1012,
    "mfgDate": "2024-03-23",
    "expiryDate": "2026-03-23",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.35,
        "dissolution": 97.85,
        "pH": 5.86,
        "moisture": 2.98,
        "impurity": 0.18,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.66,
        "dissolution": 97.53,
        "pH": 5.65,
        "moisture": 3.27,
        "impurity": 0.35,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.14,
        "dissolution": 97.23,
        "pH": 5.64,
        "moisture": 2.69,
        "impurity": 0.59,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.88,
        "dissolution": 96.65,
        "pH": 5.87,
        "moisture": 2.64,
        "impurity": 0.72,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.93,
        "dissolution": 96.37,
        "pH": 5.58,
        "moisture": 2.98,
        "impurity": 0.8,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.97,
        "dissolution": 96.13,
        "pH": 5.62,
        "moisture": 3.25,
        "impurity": 0.98,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.52,
        "dissolution": 95.81,
        "pH": 5.51,
        "moisture": 2.61,
        "impurity": 1.05,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 113,
    "medicineId": 1013,
    "mfgDate": "2024-03-23",
    "expiryDate": "2026-03-23",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.59,
        "dissolution": 98.28,
        "pH": 5.74,
        "moisture": 2.49,
        "impurity": 0.22,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.86,
        "dissolution": 97.86,
        "pH": 5.54,
        "moisture": 2.73,
        "impurity": 0.27,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.1,
        "dissolution": 97.21,
        "pH": 5.84,
        "moisture": 2.39,
        "impurity": 0.51,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.13,
        "dissolution": 96.61,
        "pH": 5.7,
        "moisture": 2.58,
        "impurity": 0.67,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.81,
        "dissolution": 96.29,
        "pH": 5.9,
        "moisture": 2.2,
        "impurity": 0.91,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.57,
        "dissolution": 95.85,
        "pH": 5.54,
        "moisture": 2.22,
        "impurity": 1.11,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.99,
        "dissolution": 95.54,
        "pH": 5.88,
        "moisture": 3.38,
        "impurity": 1.32,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 114,
    "medicineId": 1014,
    "mfgDate": "2024-03-23",
    "expiryDate": "2026-03-23",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.73,
        "dissolution": 98.36,
        "pH": 5.91,
        "moisture": 3.11,
        "impurity": 0.17,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.09,
        "dissolution": 98.17,
        "pH": 5.55,
        "moisture": 2.07,
        "impurity": 0.3,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.44,
        "dissolution": 97.85,
        "pH": 5.9,
        "moisture": 3.34,
        "impurity": 0.44,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.6,
        "dissolution": 97.73,
        "pH": 5.91,
        "moisture": 2.77,
        "impurity": 0.52,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.05,
        "dissolution": 97.54,
        "pH": 5.96,
        "moisture": 3.08,
        "impurity": 0.59,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.6,
        "dissolution": 97.08,
        "pH": 5.67,
        "moisture": 2.09,
        "impurity": 0.81,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.38,
        "dissolution": 96.82,
        "pH": 5.69,
        "moisture": 2.72,
        "impurity": 1.03,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 115,
    "medicineId": 1015,
    "mfgDate": "2024-03-22",
    "expiryDate": "2026-03-22",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.79,
        "dissolution": 97.99,
        "pH": 5.83,
        "moisture": 2.47,
        "impurity": 0.31,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.98,
        "dissolution": 97.37,
        "pH": 5.64,
        "moisture": 2.69,
        "impurity": 0.56,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.77,
        "dissolution": 96.68,
        "pH": 5.7,
        "moisture": 2.06,
        "impurity": 0.69,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.98,
        "dissolution": 96.47,
        "pH": 5.95,
        "moisture": 2.87,
        "impurity": 0.93,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.48,
        "dissolution": 96.14,
        "pH": 5.66,
        "moisture": 2.63,
        "impurity": 1.17,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 97.15,
        "dissolution": 95.67,
        "pH": 5.71,
        "moisture": 2.18,
        "impurity": 1.3,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.33,
        "dissolution": 95.15,
        "pH": 5.66,
        "moisture": 2.37,
        "impurity": 1.44,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 116,
    "medicineId": 1016,
    "mfgDate": "2024-03-26",
    "expiryDate": "2026-03-26",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99,
        "dissolution": 97.85,
        "pH": 5.56,
        "moisture": 3.09,
        "impurity": 0.2,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.18,
        "dissolution": 97.38,
        "pH": 5.65,
        "moisture": 3.32,
        "impurity": 0.44,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.96,
        "dissolution": 96.73,
        "pH": 5.69,
        "moisture": 2.77,
        "impurity": 0.58,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.01,
        "dissolution": 96.07,
        "pH": 5.67,
        "moisture": 3.01,
        "impurity": 0.64,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.2,
        "dissolution": 95.62,
        "pH": 5.57,
        "moisture": 3.05,
        "impurity": 0.78,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.77,
        "dissolution": 95.46,
        "pH": 5.78,
        "moisture": 2.71,
        "impurity": 0.88,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 94.84,
        "dissolution": 95.33,
        "pH": 5.52,
        "moisture": 2.52,
        "impurity": 1.08,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 117,
    "medicineId": 1017,
    "mfgDate": "2024-03-27",
    "expiryDate": "2026-03-27",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.3,
        "dissolution": 98.3,
        "pH": 5.53,
        "moisture": 3.08,
        "impurity": 0.28,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.36,
        "dissolution": 97.95,
        "pH": 5.6,
        "moisture": 2.89,
        "impurity": 0.34,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.67,
        "dissolution": 97.3,
        "pH": 5.9,
        "moisture": 2.49,
        "impurity": 0.44,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.24,
        "dissolution": 97.04,
        "pH": 5.65,
        "moisture": 2.46,
        "impurity": 0.68,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.76,
        "dissolution": 96.48,
        "pH": 5.81,
        "moisture": 2.65,
        "impurity": 0.77,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.55,
        "dissolution": 96.1,
        "pH": 5.93,
        "moisture": 2.4,
        "impurity": 1,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.91,
        "dissolution": 95.57,
        "pH": 5.55,
        "moisture": 2.2,
        "impurity": 1.24,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 118,
    "medicineId": 1018,
    "mfgDate": "2024-03-25",
    "expiryDate": "2026-03-25",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.22,
        "dissolution": 98.05,
        "pH": 5.64,
        "moisture": 3.11,
        "impurity": 0.17,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.73,
        "dissolution": 97.83,
        "pH": 5.93,
        "moisture": 3.41,
        "impurity": 0.26,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.81,
        "dissolution": 97.42,
        "pH": 5.96,
        "moisture": 2.61,
        "impurity": 0.34,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.49,
        "dissolution": 97.13,
        "pH": 5.52,
        "moisture": 3.02,
        "impurity": 0.44,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.99,
        "dissolution": 96.84,
        "pH": 5.6,
        "moisture": 3.06,
        "impurity": 0.61,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.61,
        "dissolution": 96.49,
        "pH": 5.78,
        "moisture": 2.02,
        "impurity": 0.71,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.95,
        "dissolution": 96.07,
        "pH": 5.88,
        "moisture": 2.97,
        "impurity": 0.85,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 119,
    "medicineId": 1019,
    "mfgDate": "2024-03-27",
    "expiryDate": "2026-03-27",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.23,
        "dissolution": 98.26,
        "pH": 5.71,
        "moisture": 2.33,
        "impurity": 0.35,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.41,
        "dissolution": 98.06,
        "pH": 5.91,
        "moisture": 3.25,
        "impurity": 0.46,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.79,
        "dissolution": 97.85,
        "pH": 5.78,
        "moisture": 3.4,
        "impurity": 0.58,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.27,
        "dissolution": 97.18,
        "pH": 5.83,
        "moisture": 2.35,
        "impurity": 0.73,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.84,
        "dissolution": 96.63,
        "pH": 5.61,
        "moisture": 3.12,
        "impurity": 0.81,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.3,
        "dissolution": 96.12,
        "pH": 5.97,
        "moisture": 2.72,
        "impurity": 1,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.32,
        "dissolution": 95.83,
        "pH": 5.86,
        "moisture": 2.04,
        "impurity": 1.23,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 120,
    "medicineId": 1020,
    "mfgDate": "2024-03-24",
    "expiryDate": "2026-03-24",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.36,
        "dissolution": 98.11,
        "pH": 5.93,
        "moisture": 3.07,
        "impurity": 0.33,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.73,
        "dissolution": 97.99,
        "pH": 5.74,
        "moisture": 2.46,
        "impurity": 0.56,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.84,
        "dissolution": 97.62,
        "pH": 5.58,
        "moisture": 2.77,
        "impurity": 0.73,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 96.94,
        "dissolution": 97.41,
        "pH": 5.56,
        "moisture": 2.74,
        "impurity": 0.82,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.61,
        "dissolution": 96.91,
        "pH": 5.83,
        "moisture": 2.37,
        "impurity": 0.89,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.41,
        "dissolution": 96.46,
        "pH": 5.74,
        "moisture": 2.5,
        "impurity": 0.97,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.56,
        "dissolution": 95.85,
        "pH": 5.83,
        "moisture": 3.47,
        "impurity": 1.11,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 121,
    "medicineId": 1001,
    "mfgDate": "2024-07-16",
    "expiryDate": "2026-07-16",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.23,
        "dissolution": 98.17,
        "pH": 5.64,
        "moisture": 3.15,
        "impurity": 0.34,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.61,
        "dissolution": 97.76,
        "pH": 5.88,
        "moisture": 3.47,
        "impurity": 0.55,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.84,
        "dissolution": 97.15,
        "pH": 5.6,
        "moisture": 2.18,
        "impurity": 0.69,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.15,
        "dissolution": 96.51,
        "pH": 5.81,
        "moisture": 2.33,
        "impurity": 0.93,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.57,
        "dissolution": 96.22,
        "pH": 5.71,
        "moisture": 2.03,
        "impurity": 1.18,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.89,
        "dissolution": 95.95,
        "pH": 5.76,
        "moisture": 3.32,
        "impurity": 1.37,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.46,
        "dissolution": 95.5,
        "pH": 5.61,
        "moisture": 2.8,
        "impurity": 1.62,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 122,
    "medicineId": 1002,
    "mfgDate": "2024-06-08",
    "expiryDate": "2026-06-08",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.64,
        "dissolution": 98.16,
        "pH": 5.6,
        "moisture": 3.32,
        "impurity": 0.18,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.99,
        "dissolution": 97.96,
        "pH": 5.98,
        "moisture": 2.27,
        "impurity": 0.32,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.29,
        "dissolution": 97.39,
        "pH": 5.7,
        "moisture": 3.07,
        "impurity": 0.49,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.75,
        "dissolution": 96.71,
        "pH": 5.68,
        "moisture": 3.31,
        "impurity": 0.7,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.33,
        "dissolution": 96.08,
        "pH": 5.57,
        "moisture": 2.83,
        "impurity": 0.86,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.44,
        "dissolution": 95.95,
        "pH": 5.65,
        "moisture": 3.18,
        "impurity": 1,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.52,
        "dissolution": 95.47,
        "pH": 5.6,
        "moisture": 3.47,
        "impurity": 1.06,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 123,
    "medicineId": 1003,
    "mfgDate": "2024-07-24",
    "expiryDate": "2026-07-24",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.35,
        "dissolution": 97.84,
        "pH": 5.58,
        "moisture": 2.14,
        "impurity": 0.16,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.49,
        "dissolution": 97.16,
        "pH": 5.95,
        "moisture": 2.54,
        "impurity": 0.28,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.89,
        "dissolution": 96.72,
        "pH": 5.51,
        "moisture": 2.29,
        "impurity": 0.5,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.15,
        "dissolution": 96.29,
        "pH": 5.74,
        "moisture": 2.84,
        "impurity": 0.71,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.57,
        "dissolution": 95.64,
        "pH": 5.57,
        "moisture": 3.09,
        "impurity": 0.77,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.88,
        "dissolution": 95.27,
        "pH": 5.98,
        "moisture": 2.54,
        "impurity": 0.87,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.07,
        "dissolution": 94.68,
        "pH": 5.9,
        "moisture": 2.94,
        "impurity": 1.07,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 124,
    "medicineId": 1004,
    "mfgDate": "2024-08-12",
    "expiryDate": "2026-08-12",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.7,
        "dissolution": 97.98,
        "pH": 5.75,
        "moisture": 2.65,
        "impurity": 0.27,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.46,
        "dissolution": 97.35,
        "pH": 5.62,
        "moisture": 2.91,
        "impurity": 0.47,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.6,
        "dissolution": 97.16,
        "pH": 5.88,
        "moisture": 3.29,
        "impurity": 0.57,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.7,
        "dissolution": 96.83,
        "pH": 5.58,
        "moisture": 2.03,
        "impurity": 0.66,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.82,
        "dissolution": 96.21,
        "pH": 5.6,
        "moisture": 2.5,
        "impurity": 0.77,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.85,
        "dissolution": 96.08,
        "pH": 5.72,
        "moisture": 2.07,
        "impurity": 0.98,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.45,
        "dissolution": 95.56,
        "pH": 5.65,
        "moisture": 3.09,
        "impurity": 1.08,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 125,
    "medicineId": 1005,
    "mfgDate": "2024-04-19",
    "expiryDate": "2026-04-19",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.61,
        "dissolution": 97.91,
        "pH": 5.61,
        "moisture": 2.72,
        "impurity": 0.34,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.11,
        "dissolution": 97.8,
        "pH": 5.96,
        "moisture": 2.2,
        "impurity": 0.54,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.18,
        "dissolution": 97.32,
        "pH": 5.64,
        "moisture": 2.52,
        "impurity": 0.6,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.38,
        "dissolution": 96.95,
        "pH": 5.84,
        "moisture": 2.4,
        "impurity": 0.81,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.68,
        "dissolution": 96.52,
        "pH": 5.87,
        "moisture": 3.47,
        "impurity": 1.05,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.88,
        "dissolution": 95.83,
        "pH": 5.53,
        "moisture": 3.38,
        "impurity": 1.14,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.24,
        "dissolution": 95.38,
        "pH": 5.92,
        "moisture": 3.3,
        "impurity": 1.38,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 126,
    "medicineId": 1006,
    "mfgDate": "2024-08-31",
    "expiryDate": "2026-08-31",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.46,
        "dissolution": 98.17,
        "pH": 5.79,
        "moisture": 2.01,
        "impurity": 0.21,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.88,
        "dissolution": 97.96,
        "pH": 5.96,
        "moisture": 2.9,
        "impurity": 0.38,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.99,
        "dissolution": 97.49,
        "pH": 5.95,
        "moisture": 2.45,
        "impurity": 0.58,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.35,
        "dissolution": 97.18,
        "pH": 5.66,
        "moisture": 2.66,
        "impurity": 0.77,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.47,
        "dissolution": 96.5,
        "pH": 5.79,
        "moisture": 3.42,
        "impurity": 0.88,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.76,
        "dissolution": 95.96,
        "pH": 5.69,
        "moisture": 2.25,
        "impurity": 1.04,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 94.79,
        "dissolution": 95.65,
        "pH": 5.66,
        "moisture": 2.59,
        "impurity": 1.18,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 127,
    "medicineId": 1007,
    "mfgDate": "2024-07-13",
    "expiryDate": "2026-07-13",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.53,
        "dissolution": 98.12,
        "pH": 5.54,
        "moisture": 2.53,
        "impurity": 0.32,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.88,
        "dissolution": 97.45,
        "pH": 5.67,
        "moisture": 2.36,
        "impurity": 0.43,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.33,
        "dissolution": 97.23,
        "pH": 5.91,
        "moisture": 2.08,
        "impurity": 0.54,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.76,
        "dissolution": 97.04,
        "pH": 5.9,
        "moisture": 2.67,
        "impurity": 0.64,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.41,
        "dissolution": 96.46,
        "pH": 5.54,
        "moisture": 2.65,
        "impurity": 0.74,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 97.19,
        "dissolution": 96.14,
        "pH": 5.6,
        "moisture": 2.57,
        "impurity": 0.85,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.58,
        "dissolution": 95.74,
        "pH": 5.88,
        "moisture": 2.38,
        "impurity": 1.04,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 128,
    "medicineId": 1008,
    "mfgDate": "2024-08-01",
    "expiryDate": "2026-08-01",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.06,
        "dissolution": 98.37,
        "pH": 5.87,
        "moisture": 2.85,
        "impurity": 0.21,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.65,
        "dissolution": 98.26,
        "pH": 5.51,
        "moisture": 2.99,
        "impurity": 0.38,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.05,
        "dissolution": 98.05,
        "pH": 5.6,
        "moisture": 2.26,
        "impurity": 0.46,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.36,
        "dissolution": 97.66,
        "pH": 5.77,
        "moisture": 3.03,
        "impurity": 0.59,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.57,
        "dissolution": 97.43,
        "pH": 5.63,
        "moisture": 3.01,
        "impurity": 0.78,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.76,
        "dissolution": 97.1,
        "pH": 5.58,
        "moisture": 2.96,
        "impurity": 1.03,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.35,
        "dissolution": 96.76,
        "pH": 5.65,
        "moisture": 3.14,
        "impurity": 1.24,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 129,
    "medicineId": 1009,
    "mfgDate": "2024-08-19",
    "expiryDate": "2026-08-19",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.24,
        "dissolution": 98.35,
        "pH": 5.88,
        "moisture": 3.35,
        "impurity": 0.27,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.8,
        "dissolution": 98.12,
        "pH": 5.95,
        "moisture": 2.18,
        "impurity": 0.42,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.82,
        "dissolution": 97.55,
        "pH": 5.63,
        "moisture": 3,
        "impurity": 0.55,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.09,
        "dissolution": 97.09,
        "pH": 5.96,
        "moisture": 2.87,
        "impurity": 0.73,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.39,
        "dissolution": 96.45,
        "pH": 5.78,
        "moisture": 3.1,
        "impurity": 0.87,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.92,
        "dissolution": 96,
        "pH": 5.91,
        "moisture": 3.26,
        "impurity": 1.1,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.23,
        "dissolution": 95.55,
        "pH": 5.62,
        "moisture": 3.42,
        "impurity": 1.32,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 130,
    "medicineId": 1010,
    "mfgDate": "2024-05-02",
    "expiryDate": "2026-05-02",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.58,
        "dissolution": 97.86,
        "pH": 5.6,
        "moisture": 2.36,
        "impurity": 0.28,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.35,
        "dissolution": 97.39,
        "pH": 5.57,
        "moisture": 2.01,
        "impurity": 0.43,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.52,
        "dissolution": 97.2,
        "pH": 5.57,
        "moisture": 2.99,
        "impurity": 0.49,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 98.24,
        "dissolution": 96.61,
        "pH": 5.67,
        "moisture": 2.54,
        "impurity": 0.68,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.95,
        "dissolution": 96.1,
        "pH": 5.55,
        "moisture": 3.14,
        "impurity": 0.75,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 97.22,
        "dissolution": 95.56,
        "pH": 5.69,
        "moisture": 3.47,
        "impurity": 0.87,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.49,
        "dissolution": 95.23,
        "pH": 5.61,
        "moisture": 3.39,
        "impurity": 0.92,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 131,
    "medicineId": 1011,
    "mfgDate": "2024-07-08",
    "expiryDate": "2026-07-08",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.14,
        "dissolution": 98.17,
        "pH": 5.79,
        "moisture": 3.31,
        "impurity": 0.21,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.56,
        "dissolution": 97.91,
        "pH": 5.69,
        "moisture": 3.37,
        "impurity": 0.26,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.02,
        "dissolution": 97.3,
        "pH": 5.63,
        "moisture": 2.04,
        "impurity": 0.45,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.4,
        "dissolution": 97.13,
        "pH": 5.61,
        "moisture": 2.02,
        "impurity": 0.66,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.74,
        "dissolution": 96.61,
        "pH": 5.55,
        "moisture": 2.74,
        "impurity": 0.9,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.93,
        "dissolution": 96.1,
        "pH": 5.54,
        "moisture": 2.28,
        "impurity": 1.08,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.35,
        "dissolution": 95.85,
        "pH": 5.99,
        "moisture": 2.3,
        "impurity": 1.14,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 132,
    "medicineId": 1012,
    "mfgDate": "2024-04-30",
    "expiryDate": "2026-04-30",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.27,
        "dissolution": 97.81,
        "pH": 5.57,
        "moisture": 2.77,
        "impurity": 0.2,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.01,
        "dissolution": 97.19,
        "pH": 5.79,
        "moisture": 3.34,
        "impurity": 0.29,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.66,
        "dissolution": 96.89,
        "pH": 5.6,
        "moisture": 3.33,
        "impurity": 0.54,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 98.01,
        "dissolution": 96.22,
        "pH": 5.93,
        "moisture": 2.85,
        "impurity": 0.6,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.69,
        "dissolution": 96.1,
        "pH": 5.98,
        "moisture": 2.03,
        "impurity": 0.84,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 97.47,
        "dissolution": 95.72,
        "pH": 5.81,
        "moisture": 2.45,
        "impurity": 0.91,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 97.09,
        "dissolution": 95.06,
        "pH": 5.56,
        "moisture": 3.06,
        "impurity": 1.03,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 133,
    "medicineId": 1013,
    "mfgDate": "2024-08-16",
    "expiryDate": "2026-08-16",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.28,
        "dissolution": 98.29,
        "pH": 5.72,
        "moisture": 2.82,
        "impurity": 0.29,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.38,
        "dissolution": 97.91,
        "pH": 5.64,
        "moisture": 2.69,
        "impurity": 0.47,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.88,
        "dissolution": 97.37,
        "pH": 5.79,
        "moisture": 2.86,
        "impurity": 0.56,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.46,
        "dissolution": 96.79,
        "pH": 5.52,
        "moisture": 3.45,
        "impurity": 0.76,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.03,
        "dissolution": 96.58,
        "pH": 5.7,
        "moisture": 2.33,
        "impurity": 1,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.07,
        "dissolution": 95.94,
        "pH": 5.8,
        "moisture": 2.61,
        "impurity": 1.18,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.46,
        "dissolution": 95.67,
        "pH": 5.82,
        "moisture": 2.85,
        "impurity": 1.43,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 134,
    "medicineId": 1014,
    "mfgDate": "2024-07-27",
    "expiryDate": "2026-07-27",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.44,
        "dissolution": 98.13,
        "pH": 5.84,
        "moisture": 2.48,
        "impurity": 0.17,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.67,
        "dissolution": 97.88,
        "pH": 5.83,
        "moisture": 2.51,
        "impurity": 0.35,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.7,
        "dissolution": 97.34,
        "pH": 5.67,
        "moisture": 2.93,
        "impurity": 0.44,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 96.79,
        "dissolution": 96.73,
        "pH": 5.55,
        "moisture": 2.66,
        "impurity": 0.58,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 95.93,
        "dissolution": 96.43,
        "pH": 5.59,
        "moisture": 3.31,
        "impurity": 0.78,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.56,
        "dissolution": 95.79,
        "pH": 5.58,
        "moisture": 3.45,
        "impurity": 0.93,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 94.87,
        "dissolution": 95.26,
        "pH": 5.94,
        "moisture": 3.34,
        "impurity": 1.17,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 135,
    "medicineId": 1015,
    "mfgDate": "2024-06-16",
    "expiryDate": "2026-06-16",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.13,
        "dissolution": 98.23,
        "pH": 5.66,
        "moisture": 2.64,
        "impurity": 0.23,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.48,
        "dissolution": 98.1,
        "pH": 5.61,
        "moisture": 2.28,
        "impurity": 0.44,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.87,
        "dissolution": 97.59,
        "pH": 5.54,
        "moisture": 2.28,
        "impurity": 0.67,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.58,
        "dissolution": 96.91,
        "pH": 5.95,
        "moisture": 3,
        "impurity": 0.84,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.89,
        "dissolution": 96.73,
        "pH": 5.75,
        "moisture": 2.13,
        "impurity": 0.92,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.65,
        "dissolution": 96.08,
        "pH": 5.86,
        "moisture": 2.97,
        "impurity": 1.12,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.26,
        "dissolution": 95.82,
        "pH": 5.86,
        "moisture": 2.01,
        "impurity": 1.22,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 136,
    "medicineId": 1016,
    "mfgDate": "2026-01-19",
    "expiryDate": "2028-01-19",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.16,
        "dissolution": 98.21,
        "pH": 5.76,
        "moisture": 3.33,
        "impurity": 0.15,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.78,
        "dissolution": 97.9,
        "pH": 5.76,
        "moisture": 3.43,
        "impurity": 0.22,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.01,
        "dissolution": 97.71,
        "pH": 5.78,
        "moisture": 3.33,
        "impurity": 0.29,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.13,
        "dissolution": 97.03,
        "pH": 5.54,
        "moisture": 2.75,
        "impurity": 0.36,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.71,
        "dissolution": 96.53,
        "pH": 5.73,
        "moisture": 2.64,
        "impurity": 0.46,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.75,
        "dissolution": 96.25,
        "pH": 5.68,
        "moisture": 2.95,
        "impurity": 0.61,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.42,
        "dissolution": 95.69,
        "pH": 5.6,
        "moisture": 3.41,
        "impurity": 0.82,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 137,
    "medicineId": 1017,
    "mfgDate": "2025-11-10",
    "expiryDate": "2027-11-10",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.55,
        "dissolution": 98.07,
        "pH": 5.93,
        "moisture": 3.33,
        "impurity": 0.28,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.17,
        "dissolution": 97.78,
        "pH": 5.95,
        "moisture": 3.31,
        "impurity": 0.37,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.79,
        "dissolution": 97.44,
        "pH": 5.78,
        "moisture": 2.7,
        "impurity": 0.46,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 98.43,
        "dissolution": 96.92,
        "pH": 5.55,
        "moisture": 3.21,
        "impurity": 0.53,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 98.14,
        "dissolution": 96.65,
        "pH": 5.68,
        "moisture": 3.04,
        "impurity": 0.68,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 97.16,
        "dissolution": 96.01,
        "pH": 5.88,
        "moisture": 2.78,
        "impurity": 0.83,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.48,
        "dissolution": 95.83,
        "pH": 5.52,
        "moisture": 3.32,
        "impurity": 1,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 138,
    "medicineId": 1018,
    "mfgDate": "2024-11-24",
    "expiryDate": "2026-11-24",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.23,
        "dissolution": 97.97,
        "pH": 5.88,
        "moisture": 2.51,
        "impurity": 0.33,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.48,
        "dissolution": 97.42,
        "pH": 5.56,
        "moisture": 2.75,
        "impurity": 0.42,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.65,
        "dissolution": 97.19,
        "pH": 5.94,
        "moisture": 2.9,
        "impurity": 0.59,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.38,
        "dissolution": 96.94,
        "pH": 5.61,
        "moisture": 3.36,
        "impurity": 0.79,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.91,
        "dissolution": 96.74,
        "pH": 5.51,
        "moisture": 2.61,
        "impurity": 1.01,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.97,
        "dissolution": 96.15,
        "pH": 5.88,
        "moisture": 2.36,
        "impurity": 1.06,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.72,
        "dissolution": 95.62,
        "pH": 5.75,
        "moisture": 2.44,
        "impurity": 1.24,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 139,
    "medicineId": 1019,
    "mfgDate": "2025-08-19",
    "expiryDate": "2027-08-19",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.13,
        "dissolution": 97.86,
        "pH": 5.57,
        "moisture": 3.05,
        "impurity": 0.3,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.25,
        "dissolution": 97.73,
        "pH": 5.59,
        "moisture": 3.48,
        "impurity": 0.53,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.71,
        "dissolution": 97.13,
        "pH": 5.86,
        "moisture": 2.54,
        "impurity": 0.74,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.43,
        "dissolution": 97,
        "pH": 5.57,
        "moisture": 2.94,
        "impurity": 0.8,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.52,
        "dissolution": 96.48,
        "pH": 5.62,
        "moisture": 3.09,
        "impurity": 0.99,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.97,
        "dissolution": 95.88,
        "pH": 5.77,
        "moisture": 2.24,
        "impurity": 1.22,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.38,
        "dissolution": 95.36,
        "pH": 5.9,
        "moisture": 2.02,
        "impurity": 1.4,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 140,
    "medicineId": 1020,
    "mfgDate": "2025-10-11",
    "expiryDate": "2027-10-11",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.77,
        "dissolution": 98.04,
        "pH": 5.74,
        "moisture": 3.31,
        "impurity": 0.16,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.09,
        "dissolution": 97.67,
        "pH": 5.87,
        "moisture": 2.28,
        "impurity": 0.29,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.36,
        "dissolution": 97.38,
        "pH": 5.78,
        "moisture": 2.37,
        "impurity": 0.44,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.67,
        "dissolution": 96.75,
        "pH": 5.62,
        "moisture": 2.53,
        "impurity": 0.69,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.21,
        "dissolution": 96.18,
        "pH": 6,
        "moisture": 3.18,
        "impurity": 0.83,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.95,
        "dissolution": 95.92,
        "pH": 5.68,
        "moisture": 2.27,
        "impurity": 0.99,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.74,
        "dissolution": 95.74,
        "pH": 5.58,
        "moisture": 2.24,
        "impurity": 1.19,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 141,
    "medicineId": 1001,
    "mfgDate": "2025-11-25",
    "expiryDate": "2027-11-25",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.73,
        "dissolution": 98.24,
        "pH": 5.58,
        "moisture": 3.47,
        "impurity": 0.26,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.89,
        "dissolution": 97.58,
        "pH": 5.94,
        "moisture": 3.25,
        "impurity": 0.41,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.36,
        "dissolution": 97.22,
        "pH": 5.93,
        "moisture": 3.08,
        "impurity": 0.6,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.83,
        "dissolution": 96.9,
        "pH": 5.94,
        "moisture": 2.69,
        "impurity": 0.69,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.24,
        "dissolution": 96.38,
        "pH": 5.65,
        "moisture": 3.08,
        "impurity": 0.84,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.87,
        "dissolution": 96.05,
        "pH": 5.83,
        "moisture": 2.94,
        "impurity": 1.07,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.28,
        "dissolution": 95.55,
        "pH": 5.97,
        "moisture": 2.04,
        "impurity": 1.24,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 142,
    "medicineId": 1002,
    "mfgDate": "2025-04-09",
    "expiryDate": "2027-04-09",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.12,
        "dissolution": 98.39,
        "pH": 5.9,
        "moisture": 2.21,
        "impurity": 0.25,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.28,
        "dissolution": 97.9,
        "pH": 5.53,
        "moisture": 2.92,
        "impurity": 0.39,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.43,
        "dissolution": 97.28,
        "pH": 5.54,
        "moisture": 2.92,
        "impurity": 0.48,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 96.92,
        "dissolution": 96.73,
        "pH": 5.78,
        "moisture": 2.24,
        "impurity": 0.61,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 95.94,
        "dissolution": 96.11,
        "pH": 5.91,
        "moisture": 2.4,
        "impurity": 0.85,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.63,
        "dissolution": 95.9,
        "pH": 5.59,
        "moisture": 2.17,
        "impurity": 1.04,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.4,
        "dissolution": 95.36,
        "pH": 5.79,
        "moisture": 2.32,
        "impurity": 1.25,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 143,
    "medicineId": 1003,
    "mfgDate": "2025-11-30",
    "expiryDate": "2027-11-30",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.02,
        "dissolution": 97.8,
        "pH": 5.65,
        "moisture": 2.74,
        "impurity": 0.28,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.8,
        "dissolution": 97.55,
        "pH": 5.84,
        "moisture": 2.21,
        "impurity": 0.45,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.3,
        "dissolution": 97.04,
        "pH": 5.96,
        "moisture": 2.53,
        "impurity": 0.65,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.47,
        "dissolution": 96.82,
        "pH": 5.65,
        "moisture": 3.14,
        "impurity": 0.72,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.98,
        "dissolution": 96.65,
        "pH": 5.6,
        "moisture": 3.3,
        "impurity": 0.91,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.69,
        "dissolution": 96.48,
        "pH": 5.93,
        "moisture": 2.35,
        "impurity": 1.06,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.02,
        "dissolution": 95.81,
        "pH": 5.89,
        "moisture": 2.1,
        "impurity": 1.14,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 144,
    "medicineId": 1004,
    "mfgDate": "2024-12-16",
    "expiryDate": "2026-12-16",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.52,
        "dissolution": 97.93,
        "pH": 5.75,
        "moisture": 2.08,
        "impurity": 0.34,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.03,
        "dissolution": 97.45,
        "pH": 5.8,
        "moisture": 3.38,
        "impurity": 0.57,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.65,
        "dissolution": 96.96,
        "pH": 5.77,
        "moisture": 3.26,
        "impurity": 0.72,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.7,
        "dissolution": 96.28,
        "pH": 5.99,
        "moisture": 3.09,
        "impurity": 0.89,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.24,
        "dissolution": 96.11,
        "pH": 5.75,
        "moisture": 3.36,
        "impurity": 1.03,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.49,
        "dissolution": 95.53,
        "pH": 5.85,
        "moisture": 2.5,
        "impurity": 1.24,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.93,
        "dissolution": 94.97,
        "pH": 5.64,
        "moisture": 3.31,
        "impurity": 1.46,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 145,
    "medicineId": 1005,
    "mfgDate": "2025-07-01",
    "expiryDate": "2027-07-01",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.35,
        "dissolution": 98.33,
        "pH": 5.51,
        "moisture": 2.36,
        "impurity": 0.23,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.91,
        "dissolution": 97.71,
        "pH": 5.88,
        "moisture": 2.91,
        "impurity": 0.35,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.32,
        "dissolution": 97.42,
        "pH": 5.87,
        "moisture": 2.07,
        "impurity": 0.47,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.55,
        "dissolution": 96.97,
        "pH": 5.67,
        "moisture": 2.36,
        "impurity": 0.53,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.98,
        "dissolution": 96.76,
        "pH": 5.89,
        "moisture": 2.51,
        "impurity": 0.73,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.5,
        "dissolution": 96.4,
        "pH": 5.96,
        "moisture": 2.38,
        "impurity": 0.82,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.95,
        "dissolution": 96.18,
        "pH": 6,
        "moisture": 3.24,
        "impurity": 0.89,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 146,
    "medicineId": 1006,
    "mfgDate": "2025-09-24",
    "expiryDate": "2027-09-24",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.59,
        "dissolution": 98.16,
        "pH": 5.67,
        "moisture": 2.69,
        "impurity": 0.16,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.11,
        "dissolution": 97.63,
        "pH": 5.94,
        "moisture": 3.36,
        "impurity": 0.32,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.68,
        "dissolution": 97.06,
        "pH": 5.82,
        "moisture": 3.32,
        "impurity": 0.43,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 98.26,
        "dissolution": 96.43,
        "pH": 5.73,
        "moisture": 2.65,
        "impurity": 0.54,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.5,
        "dissolution": 95.94,
        "pH": 5.94,
        "moisture": 2.76,
        "impurity": 0.67,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.87,
        "dissolution": 95.72,
        "pH": 5.76,
        "moisture": 2.6,
        "impurity": 0.89,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.07,
        "dissolution": 95.04,
        "pH": 5.68,
        "moisture": 2.48,
        "impurity": 1.01,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 147,
    "medicineId": 1007,
    "mfgDate": "2025-11-02",
    "expiryDate": "2027-11-02",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.59,
        "dissolution": 98.23,
        "pH": 5.73,
        "moisture": 2.27,
        "impurity": 0.27,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.71,
        "dissolution": 97.66,
        "pH": 5.71,
        "moisture": 2.43,
        "impurity": 0.43,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 98.21,
        "dissolution": 97,
        "pH": 5.89,
        "moisture": 2.07,
        "impurity": 0.62,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.87,
        "dissolution": 96.64,
        "pH": 5.65,
        "moisture": 2.05,
        "impurity": 0.85,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.34,
        "dissolution": 96.45,
        "pH": 5.77,
        "moisture": 3.13,
        "impurity": 1.06,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.66,
        "dissolution": 95.77,
        "pH": 5.87,
        "moisture": 2.07,
        "impurity": 1.21,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.22,
        "dissolution": 95.25,
        "pH": 5.74,
        "moisture": 3.49,
        "impurity": 1.29,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 148,
    "medicineId": 1008,
    "mfgDate": "2025-04-08",
    "expiryDate": "2027-04-08",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.17,
        "dissolution": 98.07,
        "pH": 5.73,
        "moisture": 3.42,
        "impurity": 0.27,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.31,
        "dissolution": 97.77,
        "pH": 5.9,
        "moisture": 3.31,
        "impurity": 0.49,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.88,
        "dissolution": 97.55,
        "pH": 5.52,
        "moisture": 3.18,
        "impurity": 0.66,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 96.96,
        "dissolution": 97.16,
        "pH": 5.69,
        "moisture": 2.17,
        "impurity": 0.83,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.63,
        "dissolution": 96.86,
        "pH": 5.87,
        "moisture": 3.27,
        "impurity": 1.05,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 95.84,
        "dissolution": 96.74,
        "pH": 5.61,
        "moisture": 2.43,
        "impurity": 1.24,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.63,
        "dissolution": 96.18,
        "pH": 5.82,
        "moisture": 3,
        "impurity": 1.42,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 149,
    "medicineId": 1009,
    "mfgDate": "2024-10-27",
    "expiryDate": "2026-10-27",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.73,
        "dissolution": 98.27,
        "pH": 5.89,
        "moisture": 3.47,
        "impurity": 0.29,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 99.28,
        "dissolution": 98.07,
        "pH": 5.8,
        "moisture": 2.6,
        "impurity": 0.42,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 99.02,
        "dissolution": 97.58,
        "pH": 5.87,
        "moisture": 3.44,
        "impurity": 0.49,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 98.31,
        "dissolution": 97.14,
        "pH": 5.66,
        "moisture": 2.63,
        "impurity": 0.66,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 97.44,
        "dissolution": 96.58,
        "pH": 5.84,
        "moisture": 2.76,
        "impurity": 0.78,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 97.2,
        "dissolution": 96.31,
        "pH": 5.82,
        "moisture": 2.66,
        "impurity": 1.01,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 96.49,
        "dissolution": 95.78,
        "pH": 5.99,
        "moisture": 2.41,
        "impurity": 1.1,
        "microbial": 10,
        "passFail": true
      }
    ]
  },
  {
    "id": 150,
    "medicineId": 1010,
    "mfgDate": "2025-04-24",
    "expiryDate": "2027-04-24",
    "testIntervals": [
      {
        "month": 0,
        "assay": 99.06,
        "dissolution": 98.15,
        "pH": 5.64,
        "moisture": 3.36,
        "impurity": 0.32,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 3,
        "assay": 98.08,
        "dissolution": 97.84,
        "pH": 5.77,
        "moisture": 2.74,
        "impurity": 0.41,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 6,
        "assay": 97.8,
        "dissolution": 97.67,
        "pH": 5.76,
        "moisture": 2.83,
        "impurity": 0.58,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 9,
        "assay": 97.24,
        "dissolution": 97.48,
        "pH": 5.82,
        "moisture": 2.82,
        "impurity": 0.66,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 12,
        "assay": 96.88,
        "dissolution": 97.33,
        "pH": 5.86,
        "moisture": 2.91,
        "impurity": 0.77,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 18,
        "assay": 96.05,
        "dissolution": 97.2,
        "pH": 5.67,
        "moisture": 2.61,
        "impurity": 0.86,
        "microbial": 10,
        "passFail": true
      },
      {
        "month": 24,
        "assay": 95.43,
        "dissolution": 96.91,
        "pH": 5.84,
        "moisture": 2.58,
        "impurity": 1.05,
        "microbial": 10,
        "passFail": true
      }
    ]
  }
];

export const BATCH_LIST = BATCHES.map(b => {
  const med = MEDICINES.find(m => m.id === b.medicineId)!;
  const status = getStatus(b.expiryDate);
  const days = daysFromNow(b.expiryDate);
  const lastTest = b.testIntervals[b.testIntervals.length - 1]! || { assay: 100 }; // fallback
  return { ...b, med, status, days, lastTest };
});

export const STATUS_COUNTS = {
  Expired:  BATCH_LIST.filter(b => b.status === 'Expired').length,
  Critical: BATCH_LIST.filter(b => b.status === 'Critical').length,
  Warning:  BATCH_LIST.filter(b => b.status === 'Warning').length,
  Safe:     BATCH_LIST.filter(b => b.status === 'Safe').length,
};

export const expiryDistributionData = [
  { name: 'Expired',  value: STATUS_COUNTS.Expired,  fill: '#ef4444' },
  { name: 'Critical', value: STATUS_COUNTS.Critical, fill: '#dc2626' },
  { name: 'Warning',  value: STATUS_COUNTS.Warning,  fill: '#f59e0b' },
  { name: 'Safe',     value: STATUS_COUNTS.Safe,     fill: '#22c55e' },
];

const mfgCounts: Record<string, number> = {};
BATCH_LIST.forEach(b => {
  const key = b.mfgDate.slice(0, 7);
  mfgCounts[key] = (mfgCounts[key] || 0) + 1;
});
export const manufactureDateData = Object.entries(mfgCounts)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([month, count]) => ({ month, batches: count }));

const expCounts: Record<string, number> = {};
BATCH_LIST.forEach(b => {
  if (b.days > 0) {
    const key = b.expiryDate.slice(0, 7);
    expCounts[key] = (expCounts[key] || 0) + 1;
  }
});
export const expiryByMonthData = Object.entries(expCounts)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([month, count]) => ({ month, batches: count }));

export const potencyTrendData = [0, 3, 6, 9, 12].map(month => {
  const row: Record<string, number | string> = { month: `${month}m` };
  MEDICINES.forEach(med => {
    const batches = BATCHES.filter(b => b.medicineId === med.id);
    if(batches.length===0) return;
    const avg = batches.reduce((sum, b) => {
      const t = b.testIntervals.find(ti => ti.month === month);
      return sum + (t?.assay ?? 100);
    }, 0) / batches.length;
    row[med.name.split(' ')[0] || ('M'+med.id)] = +avg.toFixed(2);
  });
  return row;
});

export const testParamData = MEDICINES.map(med => {
  const latestTests = BATCHES.filter(b => b.medicineId === med.id).map(b => b.testIntervals[b.testIntervals.length - 1]!).filter(Boolean);
  if(latestTests.length===0) return { medicine: med.name.split(' ')[0] || ('M'+med.id), Assay:0, Dissolution:0, pH:0, Moisture:0, Impurity:0 };
  const avg = (key: keyof TestInterval) =>
    +(latestTests.reduce((s, t) => s + ((t && t[key] as number) || 0), 0) / latestTests.length).toFixed(2);
  return {
    medicine: med.name.split(' ')[0] || ('M'+med.id),
    Assay: avg('assay'),
    Dissolution: avg('dissolution'),
    pH: avg('pH'),
    Moisture: avg('moisture'),
    Impurity: avg('impurity'),
  };
});

export const passFailData = MEDICINES.map(med => {
  const allTests = BATCHES.filter(b => b.medicineId === med.id)
    .flatMap(b => b.testIntervals).filter(Boolean);
  return {
    medicine: med.name.split(' ')[0] || ('M'+med.id),
    Pass: allTests.filter(t => t.passFail).length,
    Fail: allTests.filter(t => !t.passFail).length,
  };
});

export const AUDIT_LOGS: AuditLog[] = [
  { id: 101, timestamp: new Date(NOW.getTime() - 2500000).toISOString(), user: "Admin User", action: "Report Exported", details: "Global Stability Report CSV exported successfully." },
  { id: 102, timestamp: new Date(NOW.getTime() - 86400000).toISOString(), user: "QA Manager", action: "Batch Status Updated", details: "System automatically flagged Batch #104 as Warning." },
  { id: 103, timestamp: new Date(NOW.getTime() - 172800000).toISOString(), user: "Lab Technician", action: "Medicine Registered", details: "Added new medicine profile: Omeprazole 20mg." },
  { id: 104, timestamp: new Date(NOW.getTime() - 250000000).toISOString(), user: "System", action: "Notification Created", details: "Generated batch expiry notifications." },
  { id: 105, timestamp: new Date(NOW.getTime() - 500000000).toISOString(), user: "Admin User", action: "Login", details: "Successful authentication via SSO." },
];

export const CHAMBERS: Chamber[] = [
  { id: "CH-01", name: "Long-Term Stability Alpha", temperature: "25°C ± 2°C", humidity: "60% ± 5% RH", nextCalibration: addDays(NOW, 45), status: "Active", batchCount: 15 },
  { id: "CH-02", name: "Accelerated Beta", temperature: "40°C ± 2°C", humidity: "75% ± 5% RH", nextCalibration: subMonths(NOW, 1), status: "Out of Calibration", batchCount: 0 },
  { id: "CH-03", name: "Intermediate Gamma", temperature: "30°C ± 2°C", humidity: "65% ± 5% RH", nextCalibration: addDays(NOW, 180), status: "Active", batchCount: 35 },
  { id: "CH-04", name: "Refrigerated Delta", temperature: "5°C ± 3°C", humidity: "N/A", nextCalibration: addDays(NOW, 10), status: "Maintenance", batchCount: 0 },
];

export const TASKS: SystemTask[] = [
  { id: "TSK-01", date: addDays(NOW, 0), title: "6-Month Stability Pull (Amoxicillin)", assigneeRole: "Lab Technician", status: "Pending", batchId: 102 },
  { id: "TSK-02", date: addDays(NOW, 0), title: "Approve OOS Investigation Report", assigneeRole: "QA Manager", status: "Pending", batchId: 105 },
  { id: "TSK-03", date: addDays(NOW, 1), title: "12-Month Stability Pull (Ibuprofen)", assigneeRole: "Lab Technician", status: "Pending", batchId: 103 },
  { id: "TSK-04", date: addDays(NOW, 1), title: "Review Weekly Analytics Dashboard", assigneeRole: "QA Manager", status: "Pending" },
  { id: "TSK-05", date: addDays(NOW, -1), title: "3-Month Stability Pull (Paracetamol)", assigneeRole: "Lab Technician", status: "Completed", batchId: 101 },
  { id: "TSK-06", date: addDays(NOW, 2), title: "Chamber CH-04 Defrost Maintenance", assigneeRole: "Lab Technician", status: "Pending" },
  { id: "TSK-07", date: addDays(NOW, 2), title: "Sign-off Batch #101 Phase release", assigneeRole: "QA Manager", status: "Pending", batchId: 101 },
  { id: "TSK-08", date: addDays(NOW, 5), title: "Monthly Calibration Verification", assigneeRole: "Lab Technician", status: "Pending" },
  { id: "TSK-09", date: addDays(NOW, 6), title: "Approve Supplier Audit", assigneeRole: "QA Manager", status: "Pending" },
];
